name: Build

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4      
    - name: Checkout game files
      uses: actions/checkout@v4
      with:
        repository: gwisp2/mom-libs
        ref: v2.0.2
        path: lib
    - name: Set version
      run: |
        $tag = & git describe --tags --abbrev=0 2>$null
        if ($LASTEXITCODE -eq 0 -and $tag -match '^v(\d+\.\d+\.\d+)') {
          $version = $matches[1]
          echo "VERSION=$version"
          (Get-Content ./Directory.Build.props) -replace '<DynamicVersion>.*</DynamicVersion>', "<DynamicVersion>$version</DynamicVersion>" | Set-Content ./Directory.Build.props
        } else {
          echo "No version tag found. Using default version."
          exit 0
        }
      shell: pwsh
    - name: Restore dependencies
      run: dotnet restore      
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: InvestigatorUnlocker.dll
        path: bin/Release/netstandard2.0/InvestigatorUnlocker.dll
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/Release/netstandard2.0/InvestigatorUnlocker.dll
